// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzh9CRLY6yEsOUyIno47MoCMqGBUgAyc',
    appId: '1:436288578840:web:66634fadfe9c1ff201aa6d',
    messagingSenderId: '436288578840',
    projectId: 'authflutter-c7e76',
    authDomain: 'authflutter-c7e76.firebaseapp.com',
    storageBucket: 'authflutter-c7e76.appspot.com',
    measurementId: 'G-S6VFPPE7P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4NvJiEfUzzQ98Ak8FYdqnIR8ymaBGuYU',
    appId: '1:436288578840:android:9041027a2e576fcb01aa6d',
    messagingSenderId: '436288578840',
    projectId: 'authflutter-c7e76',
    storageBucket: 'authflutter-c7e76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5o3GKXv1i2hD_CyzTg4GXfXDH47uONCM',
    appId: '1:436288578840:ios:2e8f6108eb85f2ec01aa6d',
    messagingSenderId: '436288578840',
    projectId: 'authflutter-c7e76',
    storageBucket: 'authflutter-c7e76.appspot.com',
    iosClientId: '436288578840-kkjpkof7lnk226uhte5hoiovge12vnou.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFlowFlutterRxdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5o3GKXv1i2hD_CyzTg4GXfXDH47uONCM',
    appId: '1:436288578840:ios:2e8f6108eb85f2ec01aa6d',
    messagingSenderId: '436288578840',
    projectId: 'authflutter-c7e76',
    storageBucket: 'authflutter-c7e76.appspot.com',
    iosClientId: '436288578840-kkjpkof7lnk226uhte5hoiovge12vnou.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFlowFlutterRxdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrzh9CRLY6yEsOUyIno47MoCMqGBUgAyc',
    appId: '1:436288578840:web:74de59cbb8dea1da01aa6d',
    messagingSenderId: '436288578840',
    projectId: 'authflutter-c7e76',
    authDomain: 'authflutter-c7e76.firebaseapp.com',
    storageBucket: 'authflutter-c7e76.appspot.com',
    measurementId: 'G-JPZXEWERTB',
  );
}
